spring:
  application:
    name: simple-service
management:
  security.enabled: false
endpoints:
  beans.sensitive: false
keycloak:
  auth-server-url: http://192.168.1.206:31542/auth
  realm: company-services
  resource: simple-service
  ssl-required: external
  principal-attribute: preferred_username
  use-resource-role-mappings: true